# Generated by Django 4.1.7 on 2023-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(to='portfolio.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(default=''),
        ),
    ]
