# Generated by Django 4.1.7 on 2023-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
