# Generated by Django 4.1.7 on 2023-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_details_project_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
